language: python
python:
  - "3.6"

# command to install dependencies
services:
 - postgresql 

before_script:
 - psql -c "CREATE DATABASE ireporter_test;" -U n
 - python database_config.py

 install:
  - pip install -r requirements.txt
  - pip install coveralls

 script:
  - nosetests --with-coverage --cover-package=app
  - py.test -v --cov-report term-missing --cov app
  - pytest --cov=./app


after_success: 
  - coveralls


