language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=app
  - py.test -v --cov-report term-missing --cov app
  - python -m pytest --cov=./app


after_success: 
  - coveralls

services:
 - postgresql

addons:
 postgresql: "9.5"

before_script:
 - psql -c 'CREATE DATABASE ireporter_test' -U postgres
 - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres
