language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet

scripts:
-pytest --with-coverage app/tests/v1
-nosetests --with-coverage --cover-package=app app/tests

before_script:
  - createdb test_db

after_success: 
- coveralls
- codecov --token=
