language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - DATABASE_URL="dbname='ireporterflask' host='localhost' port='5432' user='n' password='123456'"
  - APP_SETTINGS="development"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE ireporterflask;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pytest --cov-report term-missing --cov app
  - pytest --cov=./app

after_success:
  - coveralls
  - codecov 
