language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

scripts:
-pytest --with-coverage app/tests/v1
-nosetests --with-coverage --cover-package=app app/tests/v1

after_success: 
- coveralls
- codecov --token=
