language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_database;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - py.test --cov-report term-missing --cov app
  - pytest --cov=./app

after_success:
  - coveralls
  - codecov 
