language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

scripts:
  - nose2 -v --with-coverage

after_success: 
  - coveralls
